entel-me/entel

- README.md
- app/auth/components/LoginForm.tsx
- app/auth/pages/reset-password.tsx
- app/components/LandingPage/frontPagePublicList.tsx
- app/components/acceptedList.tsx
- app/components/chats/strangeMessage.tsx
- app/components/layout.module.css
- app/components/publicList.tsx
- app/core/components/LabeledTextField.tsx
- app/pages/activeLists.tsx
- app/pages/chats.tsx
- app/pages/chats/[chatId].tsx
- mailers/forgotPasswordMailer.ts
- mailers/newMessageMailer.ts
- next-env.d.ts
- package-lock.json
- package.json
- tsconfig.json
- Removed size attribute to fix chakra-ui inputs in `LabeledTextField`
- Removed port attribute from smpt to fit type
- Show "show more" on `PublicLists`s always
- other small improvements
> Added small fixes to deploy

- app/components/LandingPage/frontPage.tsx
Changing the text on the landing page
> rename landing page

- README.md
- app/auth/components/LoginForm.tsx
- app/auth/pages/reset-password.tsx
- app/components/LandingPage/frontPage.tsx
- app/components/LandingPage/frontPagePublicList.tsx
- app/components/acceptedList.tsx
- app/components/chats/strangeMessage.tsx
- app/components/layout.module.css
- app/components/publicList.tsx
- app/core/components/LabeledTextField.tsx
- app/pages/activeLists.tsx
- app/pages/chats.tsx
- app/pages/chats/[chatId].tsx
- mailers/forgotPasswordMailer.ts
- mailers/newMessageMailer.ts
- next-env.d.ts
- package-lock.json
- package.json
- tsconfig.json
- Removed size attribute to fix chakra-ui inputs in LabeledTextField
- Removed port attribute from smpt to fit type
- Show "show more" on PublicListss always
- Updated landing page
- Other small improvements
> Fixed entel for deployment

- package.json
Added start:production script to package.json
> Added start:production script

- app/pages/chats/[chatId].tsx
Added scroll to the overflow-attribute to grandparent container of messages. 
probably fixes #28 too
> Maximum height chat window

- app/components/LandingPage/frontPage.tsx
This time I'm merging to the develop branch.
> Fixed list

- app/components/LandingPage/frontPage.tsx
- app/pages/chats/[chatId].tsx
- fix chat height bug
- rename items on fontpage list
> Merge Chatfix and rename on fontpage list

- .github/workflows/build.yml
- Add a github workflow that build application completely in PRs 
fix #46
> Add github worklfow "build"

- .github/workflows/build.yml
- added branch develop to github actions
> Add develop branch to github actions

- app/pages/datenschutz.tsx
resolving the "Datenschutz-issue"
> Datenschutz issue

- app/components/layout.tsx
- public/robots.txt
- public/sitemap.xml
- Added a sitemap and robots.txt
- Added meta information
fix #50
> Add entel.me to search engines

- app/components/layout.tsx
> Git Link improved

- app/lists/components/acceptedList.tsx
- replaced BlitzLink by router.push
fix #68
> Replace Blitz-Link in AcceptList

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- added linter
- moved unittests to separate file
- added dependency cache
> Improve github actions

- .env
- .env.production
- .env.test
- README.md
- app/auth/mutations/forgotPassword.test.ts
- app/auth/queries/signup.ts
- app/pages/verify-mail.tsx
- integrations/mail.ts
- mailers/forgotPasswordMailer.ts
- mailers/newMessageMailer.ts
- mailers/verifyMailMailer.ts
- package-lock.json
- package.json
- replace preview-email by ethereal
- move transport into own file
- add to readme
- Remove second mail
> Improve mail in entel-dev environment

- .env
- .env.production
- .env.test
- README.md
- app/auth/mutations/forgotPassword.test.ts
- app/auth/mutations/forgotPassword.ts
- app/auth/mutations/verifyMail.ts
- app/chats/mutations/createAdminMessage.tsx
- app/chats/mutations/sendMessage.tsx
- emails/forgotPassword/html.hbs
- emails/forgotPassword/subject.hbs
- emails/forgotPasswordMailer.ts
- emails/newMessage/html.hbs
- emails/newMessage/subject.hbs
- emails/newMessageMailer.ts
- emails/verifyMail/html.hbs
- emails/verifyMail/subject.hbs
- emails/verifyMailMailer.ts
- integrations/mail.ts
- mailers/forgotPasswordMailer.ts
- mailers/newMessageMailer.ts
- mailers/verifyMailMailer.ts
- package-lock.json
- package.json
- added handlebars, email-templates 
- moved mailer to email
- polished emails by using handlebars
#88 should be merged before this PR
fix #34
> Polish email

- emails/forgotPasswordMailer.ts
- emails/newMessageMailer.ts
- emails/verifyMailMailer.ts
I added the origin of the a mail to the message itself. Thereby, mails aren't classified as spam anymore.
fix #96
> add from attribute to mail

- .github/workflows/lint.yml
- .github/workflows/test.yml
Fix typo in github workflows: build -> lint, build -> test
What types of changes does your code introduce to Appium?
> Fix typo in github workflows

- .github/pull_request_template.md
Fix typo in Pull Request Template: appium -> entel
> Fix typo in Pull Request Template

- app/core/components/resetPasswordForm.tsx
- app/pages/reset-password.tsx
I removed the quotation marks from the button, made the heading to a real heading and edited the width of the form.
fix #47 
What types of changes does your code introduce to Appium?
> polish reset password page

- app/pages/_app.tsx
I've moved the root error boundary into the root layout component. With that, errors will be shown in our main layout instead of a plain page.
> Add inner error boundary

- app/auth/mutations/verifyMail.ts
- app/auth/queries/signup.ts
Removes the token used for email verification if necessary and introduces `resolver.pipe`.
> remove verify mail token

- app/chats/mutations/createAdminMessage.tsx
- app/chats/mutations/createChat.tsx
- app/chats/mutations/markAdminAsRead.tsx
- app/chats/mutations/markMessagesAsRead.tsx
- app/chats/mutations/sendMessage.tsx
- app/chats/queries/getParticipantsByChatId.tsx
- app/chats/validation.ts
- app/core/mutations/updatePoisition.tsx
- app/core/queries/getPositionOfUser.tsx
- app/core/validation.ts
- app/lists/components/acceptedList.tsx
- app/lists/components/ownedList.tsx
- app/lists/components/publicList.tsx
- app/lists/mutations/acceptList.tsx
- app/lists/mutations/addItem.tsx
- app/lists/mutations/archiveList.tsx
- app/lists/mutations/createList.tsx
- app/lists/mutations/doneList.tsx
- app/lists/mutations/removeAllItems.tsx
- app/lists/mutations/removeShoppinglist.tsx
- app/lists/mutations/renewList.tsx
- app/lists/mutations/updateStoreComment.tsx
- app/lists/validation.ts
- app/pages/chats/[chatId].tsx
I added resolver and zod to mutations to validate the input. This prevents access by unauthorized. Additionally, I added some checks in "chats" to check for authorizations and stuff.
What types of changes does your code introduce to Appium?
> Add resolver and zod, fix security issues

- app/core/layouts/layout.tsx
- app/pages/activeLists.tsx
- app/pages/archivedLists.tsx
- app/pages/chats.tsx
- app/pages/chats/[chatId].tsx
- app/pages/index.tsx
Removes refetchIntervalls option and replaces rest with staleTime
> Remove RefetchIntervalls
